# Generated by Django 2.0.2 on 2018-02-26 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimeField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_null', models.BooleanField(default=True)),
                ('is_blank', models.BooleanField(default=True)),
                ('field_name', models.CharField(blank=True, max_length=255, null=True)),
                ('params', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_time_fields', models.ManyToManyField(blank=True, to='EntityBuilder.DateTimeField')),
            ],
        ),
        migrations.CreateModel(
            name='EnumField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_null', models.BooleanField(default=True)),
                ('is_blank', models.BooleanField(default=True)),
                ('field_name', models.CharField(blank=True, max_length=255, null=True)),
                ('default_value', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForeignKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_null', models.BooleanField(default=True)),
                ('is_blank', models.BooleanField(default=True)),
                ('field_name', models.CharField(blank=True, max_length=255, null=True)),
                ('link_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EntityBuilder.Entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_null', models.BooleanField(default=True)),
                ('is_blank', models.BooleanField(default=True)),
                ('field_name', models.CharField(blank=True, max_length=255, null=True)),
                ('default_value', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManyToManyField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_null', models.BooleanField(default=True)),
                ('is_blank', models.BooleanField(default=True)),
                ('field_name', models.CharField(blank=True, max_length=255, null=True)),
                ('link_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EntityBuilder.Entity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StringField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_null', models.BooleanField(default=True)),
                ('is_blank', models.BooleanField(default=True)),
                ('field_name', models.CharField(blank=True, max_length=255, null=True)),
                ('max_length', models.PositiveIntegerField(default=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='entity',
            name='enum_fields',
            field=models.ManyToManyField(blank=True, to='EntityBuilder.EnumField'),
        ),
        migrations.AddField(
            model_name='entity',
            name='foreign_keys',
            field=models.ManyToManyField(blank=True, to='EntityBuilder.ForeignKey'),
        ),
        migrations.AddField(
            model_name='entity',
            name='int_fields',
            field=models.ManyToManyField(blank=True, to='EntityBuilder.IntField'),
        ),
        migrations.AddField(
            model_name='entity',
            name='many_to_many_fields',
            field=models.ManyToManyField(blank=True, to='EntityBuilder.ManyToManyField'),
        ),
        migrations.AddField(
            model_name='entity',
            name='string_fields',
            field=models.ManyToManyField(blank=True, to='EntityBuilder.StringField'),
        ),
    ]
