# Generated by Django 2.0.2 on 2018-02-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntityBuilder', '0002_booleanfield_floatfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booleanfield',
            name='field_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datetimefield',
            name='field_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enumfield',
            name='field_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='floatfield',
            name='field_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foreignkey',
            name='field_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intfield',
            name='field_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manytomanyfield',
            name='field_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stringfield',
            name='field_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
