# Generated by Django 2.0.2 on 2018-02-27 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EntityBuilder', '0003_auto_20180227_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignkey',
            name='link_entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EntityBuilder.Entity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manytomanyfield',
            name='link_entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EntityBuilder.Entity'),
            preserve_default=False,
        ),
    ]
