# Generated by Django 2.0.2 on 2018-02-27 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EntityBuilder', '0004_auto_20180227_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnumOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(default='', max_length=32)),
                ('enum_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EntityBuilder.EnumField')),
            ],
        ),
    ]
